name: GitHub Actions Demo
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Archive binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: pseudoc.exe
          path: target/release/pseudoc.exe

      - name: Archive binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: pseudoc
          path: target/release/pseudoc
